# Cvičení 1

Začnemě opakováním základů programovacího jazyka Python, tzn. tvorbou a prací s proměnnými, cykly (`for`) a podmínkami (`if, else, elif`). Následně se zaměříme na knihovnu Numpy, která slouží k práci vektory a maticemi.

## Práce s buňkami v notebooku

Připomeňme, že buňku (cell) s kódem v Jupyter Notebooku můžeme spustit těmito příkazy:
- `Ctrl + Enter` - spustí daný řádek kódu
- `Shift + Enter` - spustí daný řádek kódu a přejde na další řádek
- `Alt + Enter` - spustí daný řádek kódu a vytvoří nový řádek pod ním

Další možnost je využít tlačítko `Execute cell` vlevo nahoře od buňky.

## Základní aritmetické operace

Notebook (resp. Python interpret samotný) můžeme využít jako kalkulátor k základním výpočtům. Výsledky nemusíme ukládat do proměnných. Zkuste spustit následující buňky.

In [ ]:
1+1

In [3]:
10*(2+3)

50

In [2]:
3*sin(3)

NameError: name 'sin' is not defined

Předchozí buňku nebylo možné spustit. Abychom mohli využívat pokročilejší matematické operace, musíme importovat příslušnou knihovnu (v tomto případě math nebo numpy). Projděte si a spusťte následující buňky.

In [1]:
import math
3*math.sin(3)           # Musíme volat s návzem knihovny "math."

0.4233600241796016

In [ ]:
from math import sin
3*sin(math.pi)          # sin můžeme volat i bez návzu knihovny, před konstantu pi musíme stále  napsat "math."

**Pozor**: Následující přístup sice funguje a načte vše z knihovny `math`, ale je považován za **špatný zvyk**. Nevíte, co vše se z knihovny načetlo, názvy importovaných proměnných a funkcí mohou **kolidovat** s vašimi názvy nebo s funkcemi načtenými z jiných knihoven.

**Nevyužívejte**, pokud to není nezbytně nutné. 

In [ ]:
from math import *
3*acos(sin(pi))         # Načte se vše z knihovny math, vše lze volat bez počátečního "math."

## Proměnné 

Proměnné definujeme pomocí znaku `=`. Typ proměnné není nutné specifikovat (Python je dynamicky typovaný jazyk, typ proměnné určí interpret jazyka automaticky).

In [ ]:
a = 5
b = math.pi
c = "Hello world"

print(a)
print(b)
print(c)

Jakého typu je daná proměnná můžeme zjistit pomocí příkazu `type`.

In [ ]:
print(type(a))
print(type(b))
print(type(c))

## `for` cyklus

Pro cyklus s předem daným počtem iterací využíváme příkaz `for`. Základní použití je v kombinaci s příkazem `range`, pomocí kterého vytvoříme tzv. iterovatelný objekt:

- `range(n)` - vytvoří iterovatelný objekt, který obsahuje čísla od 0 do n-1
- `range(m, n)` - vytvoří iterovatelný objekt, který obsahuje čísla od m do n-1
- `range(m, n, k)` - vytvoří iterovatelný objekt, který obsahuje čísla od m do n-1 s krokem k

Následující kód iteruje od 0 do 5 a vypíše současnou hodnotu `i`.

In [ ]:
for i in range(2,11):
    print(i)

In [ ]:
# UKOL: Doplňte kód, který vypíše sudá čísla od 2 do 10 (včetně):



## Podmínky

K vytváření podmíněných bloků kódu slouží příkazy `if`, `else`, `elif`.

K porovnávání mezi hodnotami používáme operátory `==`, `>=`, `<=`, `>`, `<`, `!=`

In [6]:
x = 0.5

if (abs(x) <= 1):
    y = math.acos(x)
    print("acos(x) = {}".format(y))
else:
    print("Hodnota proměnné je mimo definiční obor funkce.")

acos(x) = 1.0471975511965979


In [7]:
""" 
UKOL: Doplňte následující kód tak, aby 
1) smyčka iterovala od 1 do 20 včetně
2) vypsal aktuální i
3) pokud je aktuální i sudé, vypsal na dalším řádku "Sudé číslo"
4) pokud je aktuální i liché, vypsal na dalším řádku "Liché číslo"

K určení toho, zda je číslo sudé, potřebujete modulo operátor % - zbytek po 
celočíselném deleni. (zbytek = delenec % delitel) 

"""

for i in range(1,21):
    print(i)
    if((i % 2) == 0):
        print("Sude")
    else:
        print("Liche")

1
Liche
2
Sude
3
Liche
4
Sude
5
Liche
6
Sude
7
Liche
8
Sude
9
Liche
10
Sude
11
Liche
12
Sude
13
Liche
14
Sude
15
Liche
16
Sude
17
Liche
18
Sude
19
Liche
20
Sude


## Knihovna NumPy

V tomto kurzu budeme pracovat hlavně s knihovnou `NumPy`, základní knihovnou pro vědecké výpočty v Pythonu. Umožňuje nám manipulaci s vektory a maticemi, implementuje operace mezi nimi či maticové rozklady.

In [2]:
import numpy as np      #  np je běžně využívaná zkratka pro numpy

Matice a vektory můžeme vytvořit např. pomocí:

- `np.array()` - vytvoří vektor/matici z listu
- `np.zeros()` - vytvoří vektor/matici o daných rozměrech, která je naplněna nulami
- `np.ones()` - vytvoří vektor/matici o daných rozměrech, která je naplněna jedničkami
- `np.linspace()` - vytvoří vektor o daných rozměrech, který obsahuje čísla od m do n-1 s krokem k
- `np.eye()` - vytvoří jednotkovou matici o daných rozměrech
- `np.random.rand()` - vytvoří vektor/matici o daných rozměrech, která je naplněna náhodnými čísly z intervalu [0, 1)

(Vzpomeňte si, že dokumentaci k jednotlivým funkcím s detailnějším popisem můžete zavolat pomocí příkazu `help`, např. `help(np.linspace)`)

Příklady použití:

In [10]:
import numpy as np
b = np.array([1, 2, 3, 4])
print(b)

[1 2 3 4]


In [11]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A) 

[[1 2 3]
 [4 5 6]]


In [ ]:
e = np.ones(4)
print(e)

In [12]:
I = np.eye(5)
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [23]:
"""
ÚKOL: 
1) Vytvořte matici A samých nul, která má 4 řádky a 3 sloupce.
2) Vytvořte náhodný vektor b o čtyřech prvcích.
3) Vytvořte vektor v obsahující 10 čísel rovnoměrně rozmístěných mezi 0 a 5 včetně.
"""

import numpy as np

A = np.zeros((4, 3))
print(A)
b = np.random.rand(4)
print(b)
v = np.linspace(0, 5, 10)
print(v)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[0.52029831 0.27329469 0.49998074 0.09761641]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


Chceme-li přistupovat k prvkům matice či vektoru v NumPy, využíváme hranaté závorky `[]` a indexujeme od nuly. 

In [34]:
b = np.array([0, 1, 2, 3, 4])
print(b)

x = b[1]        # druhý prvek vektoru b
print(x)

x = b[0:3]      # prvky na pozicích 0 až 2
print(x)

x = b[0:5:2]    # každý druhý prvek vektoru, (zopakujme syntaxi: x = b[start:end+1:krok])
print(x)

x = b[[1, 3]]   # prvky na pozicích 1, 3
print(x)

x = b[-1]       # můžeme indexovat odzadu, indexem -1 získáme poslední prvek, -2 předposlední, atd.
print(x)

[0 1 2 3 4]
1
[0 1 2]
[0 2 4]
[1 3]
4


In [ ]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(A)

a = A[0, 0]         # prvek na pozici (0, 0)
print(a)

a = A[1, 3]         # prvek na pozici (1, 3)
print(a)

B = A[0, 1:3]       # prvky na prvním řádku v druhém až třetím sloupci (v řeči indexů - na 0. řádku a 1. až 3. sloupci bez 3. sloupce)
print(B)

In [36]:
"""
ÚKOL: 
1) Vytvořte náhodnou matici o rozměrech 5x5.
2) Do vektoru v uložte poslední řádek matice, vektor vytiskněte.
3) Do vektoru u uložte prvky na druhém řádku matice v prvním a posledním sloupci, vytiskněte.
"""
import numpy as np

A = np.random.rand(5, 5)
print(A)
v = A[4, 0:5]
print(v)
u = A[1, 0:5:4]
print(u)


[[0.8919501  0.0071254  0.29892122 0.33484246 0.50027446]
 [0.13371433 0.76354881 0.1433816  0.95617005 0.82559421]
 [0.61817329 0.61162661 0.69140988 0.90430277 0.70242382]
 [0.3869835  0.42514086 0.02582873 0.21304319 0.08892213]
 [0.01727113 0.1913814  0.90190576 0.47721735 0.21627095]]
[0.01727113 0.1913814  0.90190576 0.47721735 0.21627095]
[0.13371433 0.82559421]


Vektory v NumPy mohou být reprezentovány jako 
1) 1D pole, např. `x = np.array([1, 2, 3])` nebo `y = ones(6)`
2) 2D pole ve formě řádku, např. `x = np.array([[1, 2, 3]])` nebo `y = np.zeros((1, 4))`
3) 2D pole ve formě sloupce, např. `x = np.array([[1], [2], [3]])`, `y = np.zeros((5, 1))` nebo `y = np.array([[1, 2, 3]]).T`

Vzhledem k tomu, že vektory budeme využívat zejména k účelům algoritmů lineární algebry, doporučuji vám je rovnou vytvářet ve 2D formě jako řádek nebo sloupec. Další možnost je vytvořit 1D pole a to _reshapovat_ na správné rozměry.

In [38]:
x = np.array([1, 2, 3])     # vytvoří 1D pole (ani řádek, ani sloupec)
x = x.reshape(3, 1)         # konvertuje x na 2D sloupcový vektor
print(x)
print(np.shape(x))          # vytiskne rozměry x 

print("---------------------")

y = np.array([1, 2, 3]).T   # vytvoříme řádkový vektor a transponujeme jej
print(y)
print(np.shape(y))

[[1]
 [2]
 [3]]
(3, 1)
---------------------
[1 2 3]
(3,)


In [39]:
"""
ÚKOL: 
1) Vytvořte náhodný sloupcový vektor x délky 5 a náhodný řádkový vektor y délky 5
2) Pomocí vhodných funkcí z knihovny NumPy určete 
    - normu vektoru x
    - skalární součin vektoru y s vektorem x
    - součet vektoru x s transpozicí vektoru y
"""
import numpy as np
x = np.random.rand(5)
x = x.reshape(5, 1)
y = np.random.rand(5)
y = y.reshape(1, 5)

n = np.linalg.norm(x)
print(n)

skal = np.dot(y, x)
print(skal)

sum = x + np.transpose(y)
print(sum)

1.1960387337377236
[[0.78844685]]
[[0.74667098]
 [0.31253808]
 [0.6085631 ]
 [1.48244747]
 [0.91359404]]


In [ ]:
"""
ÚKOL:
Vypočítejte nyní normu vektoru x a skalární součin y*x "manuálně" pomocí cyklů for.
"""





NumPy podporuje také samozřejmě také násobení matice s vektorem či matice s maticí. K tomu lze využít funkci `matmul` nebo operátor `@`.

In [ ]:
A = np.ones((3, 3))
x = np.array([0, 1, 2])
x = x.reshape(3, 1)         # převedeme x na sloupcový vektor abychom jím mohli násobit matici zprava

y = np.matmul(A, x)         # násobení pomocí matmul
print(y)

z = A @ x                   # násobení pomocí operátoru @
print(y)

B = np.random.rand(3, 3)
C = np.matmul(A, B)
print(C)

In [40]:
"""
ÚKOL:
Do funkce muj_matvec implementujte vaši verzi násobení matice s vektorem.
Využijte dvě vnořené smyčky for. Na vstupu bude matice A a sloupcový vektor x 
odpovídající délky. Funkce bude vracet vektor y = Ax.
"""

def muj_matvec(A, x):
    m, n = np.shape(A)      # tuple unpacking, m obsahuje počet řádků, n počet sloupců matice A
    y = 

    for i in 
        for j in 
            

    return y

In [ ]:
# Zde si voláním funkce ověřte, zda funguje správně:

A = np.random.rand(3, 4)
x = np.random.rand(4, 1)
y = muj_matvec(A, x)
print(y)        # vytiskneme výsledek z vaší funkce

yy = A @ x
print(yy)       # porovnejte s voláním zabudované numpy funkce

In [ ]:
# Porovnáme časy výpočtu pomocí vaší funkce a zabudované numpy funkce
import time

A = np.random.rand(2000, 2000)
x = np.random.rand(2000, 1)

# otestujeme vaši implementaci 
st = time.time()
y = muj_matvec(A, x)
et = time.time()

your_time = et - st

# otestujeme zabudovanou implementaci
st = time.time()
yy = A @ x
et = time.time()

numpy_time = et - st

print("Čas výpočtu pomocí vaší funkce: {} sekund".format(your_time))
print("Čas výpočtu pomocí numpy funkce: {} sekund".format(numpy_time))

Implementujte nyní násobení matice-vektor na základě předpisu $$A\mathbf{x} = \sum_{i=1}^n x_i \mathbf{a}_i,$$
kde $\mathbf{a}_i$ je $i$-tý sloupec matice $A$ a $x_i$ je příslušný prvek vektoru $\mathbf{x}$.

Nápověda: budete-li chtít vytáhnout sloupec matice pomocí příkazu `A[:, i]`, NumPy redukuje dimenzi a vrátí 1D vektor. Pro získání 2D sloupcového vektoru je třeba zavolat `A[:, [i]]`.

In [25]:
# ÚKOL: Doplňte implementaci.

def muj_matvec_v2(A, x):
    

In [ ]:
# Ověřte funkčnost :



In [ ]:
# Otestujte na stejně velké matici jako vaši předchozí verzi a porovnejte výpočetní časy. 
# Liší se časy významně? Pokud ano, pokuste se zdůvodnit proč.

A = np.random.rand(2000, 2000)
x = np.random.rand(2000, 1)

# otestujeme vaši implementaci 
st = time.time()
y = muj_matvec_v2(A, x)
et = time.time()

your_time = et - st

# otestujeme zabudovanou implementaci
st = time.time()
yy = A @ x
et = time.time()

numpy_time = et - st

print("Čas výpočtu pomocí vaší funkce: {} sekund".format(your_time))
print("Čas výpočtu pomocí numpy funkce: {} sekund".format(numpy_time))

In [ ]:
# Bonus: Pokuste se implementovat funkci mat_mat, která bude násobit dvě matice. 
# Porovnejte výkon s funkcí z knihovny NumPy.
